# ===========================================================================
# NEON Driver Cascade — ui.R
# ===========================================================================
ui <- bslib::page_sidebar(
  theme = app_theme, title = NULL,
  window_title = "NEON Driver Cascade", fillable = FALSE,
  tags$head(
    tags$link(rel = "preconnect", href = "https://fonts.googleapis.com"),
    tags$link(rel = "preconnect", href = "https://fonts.gstatic.com", crossorigin = NA),
    tags$link(rel = "stylesheet", href = "https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700;800&display=swap"),
    tags$link(rel = "stylesheet", href = asset_url("styles.css")),
    tags$link(rel = "stylesheet", href = asset_url("cascade.css")),
    tags$script(src = asset_url("cascade.js"))
  ),
  useShinyjs(),
  sidebar = sidebar(
    width = 330, class = "control-deck",
    div(class = "brand", div(class = "brand-mark", "\U0001F517"),
      div(div(class = "brand-title", "Driver Cascade"), div(class = "brand-sub", "NEON · cross-product synthesis"))),
    selectInput("site", label = tagList(bs_icon("pin-map-fill"), " Site"),
                choices = cascade_site_choices(), selected = DEFAULT_SITE, width = "100%"),
    uiOutput("siteBio"),
    uiOutput("signalChips"),
    hr(class = "deck-hr"),
    selectInput("response", label = tagList(bs_icon("bullseye"), " Driver Lab: explain…"),
                choices = c("Small-mammal catch rate" = "mammal_cpue",
                            "Plant richness" = "plant_richness", "Green-up onset" = "greenup_doy"),
                selected = "mammal_cpue", width = "100%"),
    hr(class = "deck-hr"),
    actionButton("help", tagList(bs_icon("question-circle"), " How to read this"), class = "btn-outline-dark btn-sm w-100"),
    div(class = "theme-toggle-row", tags$span(class = "theme-toggle-lab", bs_icon("circle-half"), " Theme"),
      input_dark_mode(id = "colorMode", mode = "light")),
    div(class = "deck-foot", bs_icon("diagram-3"), " 5 NEON products, one cascade",
      br(), tags$a(href = "https://desertdatalabs.com", target = "_blank", bs_icon("box-arrow-up-right"), " Desert Data Labs"))
  ),
  uiOutput("heroStats"),
  div(class = "main-tabs-wrap",
    navset_card_tab(id = "tabs",
      nav_panel(title = tagList(bs_icon("compass"), " Overview"), value = "overview",
        card(card_head("diagram-3-fill", "The idea: populations are driven from the bottom up",
          info_pop("The cascade",
            p("Five NEON products, normally explored apart, share field sites. This app lines them up by year into one ", tags$b("bottom-up cascade"), ":"),
            p(tags$b("climate"), " sets the water and warmth → ", tags$b("green-up timing"), " (the hinge) → ", tags$b("producers"), " (plants) → ", tags$b("consumers"), " (small mammals, birds)."),
            p(class = "caveat", bs_icon("exclamation-triangle"), " Each site has only a handful of years. This tool ", tags$b("states what the literature predicts"), " and checks whether the data agrees — it does ", tags$b("not"), " hunt for whichever correlation looks biggest."))),
          uiOutput("overviewInsight"),
          div(class = "cascade-strip", uiOutput("cascadeSchematic")),
          uiOutput("standingStock")),
        card(card_head("list-check", "What's measured here", info_pop("Signals", p("The annual signals available at this site, by trophic layer."))),
          uiOutput("signalTable")),
        handoff("See the cascade year by year", "ladder")),

      nav_panel(title = tagList(bs_icon("bar-chart-steps"), " Cascade Ladder"), value = "ladder",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("The cascade, year by year",
             info_pop("Reading the ladder",
               p("Each strip is one trophic layer; each line a signal, ", tags$b("standardised"), " (z-scored) so layers are comparable on one scale. Shared x-axis = year."),
               p("Watch whether pulses ", tags$b("march down the ladder"), " — a wet year, then a green flush, then more plants, then more rodents. The chips on the right show whether each link matches its ", tags$b("literature-predicted direction"), "."),
               p(class = "caveat", bs_icon("exclamation-triangle"), " Short series: read the shapes, not a single number. Verdicts are gated by how many years overlap."))),
          p("Standardised annual signals, stacked by trophic layer. The eye does the judging; the chips keep it honest."))),
        uiOutput("pulseBanner"),
        layout_columns(col_widths = c(8, 4),
          card(full_screen = TRUE, card_head("bar-chart-steps", "Alignment ladder"),
            div(class = "ladder-note", bs_icon("info-circle"),
              tags$span(HTML("Each line is <b>standardised</b>"), cpop("zscore"), HTML(": <b>0 = that signal's own average year</b>, up = above average, down = below. Compare the <b>timing</b> of the bumps across strips, not their heights — and each link carries a <b>lag</b>"), cpop("lag"), HTML(". Each strip's lines share its layer's colour."))),
            spin(plotlyOutput("ladderPlot", height = "560px"))),
          card(card_head("link-45deg", "Do the links match the prior?",
            info_pop("Link chips", p("Each arrow is a predicted driver→response link with its expected sign and lag. The colour says whether the data agrees, and is honest about how few years stand behind it."))),
            uiOutput("linkChips"))),
        card(card_head("droplet-half", "Seasonal climate — why one annual number isn't enough",
          info_pop("Seasonal split",
            p("In bimodal deserts, rain comes in two ecologically independent seasons — ", tags$b("winter"), " (Oct–Mar, which grows the spring forbs) and the ", tags$b("summer monsoon"), " (Jul–Sep, which grows the grass seeds desert rodents eat)."),
            p("They can even move in opposite directions from year to year, so a single ", tags$b("annual"), " rainfall total blends them into noise. Splitting them back out is what recovers the desert cascade."))),
          uiOutput("seasonalPanel"),
          spin(plotlyOutput("seasonalPlot", height = "300px"))),
        handoff("Why does a rung miss here? Open the Driver Lab", "lab")),

      nav_panel(title = tagList(bs_icon("bullseye"), " Driver Lab"), value = "lab",
        div(class = "tab-head", div(class = "tab-head-text",
          h4(textOutput("labTitle", inline = TRUE),
             info_pop("Driver Lab",
               p("For the response you pick (left), every candidate driver the literature proposes — its expected ", tags$b("sign"), " and ", tags$b("lag"), " — checked against this site's data."),
               p("At ", tags$b("n < 6 years"), " no verdict is given (the series is too short); links are shown as ", tags$b("exploratory"), ". A permutation null + bootstrap CI gate the rest. Never read these as causation."))),
          p("Which drivers explain this response here — measured against what ecology predicts, not against whichever lag looks best."))),
        uiOutput("signMatchBanner"),
        layout_columns(col_widths = c(7, 5),
          card(full_screen = TRUE, card_head("table", "Predicted drivers vs. the data"),
            uiOutput("driverTable")),
          card(full_screen = TRUE, card_head("graph-up", "Selected link — the aligned pairs",
            info_pop("Scatter", p("The driver (x) against the response (y) at the predicted lag, one point per overlapping year. Few points = wide uncertainty; that's the honest picture."))),
            spin(plotlyOutput("linkScatter", height = "330px")),
            uiOutput("linkScatterNote"),
            uiOutput("scatterDetail"))),
        handoff("Does this hold across all of NEON?", "suite")),

      nav_panel(title = tagList(bs_icon("grid-3x3-gap-fill"), " Across NEON"), value = "suite",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Does the cascade hold across NEON?",
             info_pop("The scoreboard",
               p("One site's handful of years can't settle anything. But each predicted link can be ", tags$b("pooled across the sites where it's expected"), " — one vote per site — which is the statistically honest way past the short-series problem."),
               p("The grid shows every link's verdict at every site. ", tags$b("Green"), " columns marching down a biome block mean the mechanism holds there; ", tags$b("grey"), " means too few years to tell — and we show that, rather than hide it."))),
          p("Per-site series are short; pooled across sites, the picture is clear. Each cell is one link's verdict at one site — click any site to open it."))),
        card(card_head("trophy", "The pooled result — the cascade's one robust rung"), uiOutput("pooledHeadline")),
        card(full_screen = TRUE, card_head("grid-3x3-gap", "Site × link sign-match grid",
          info_pop("Reading the grid", p("Rows are sites grouped by biome; columns are the predicted links. Cell colour = the verdict; faded cells aren't the mechanism expected for that biome.")),
          downloadButton("dlSuite", tagList(bs_icon("filetype-csv"), " CSV"), class = "btn-outline-dark btn-sm ms-auto")),
          div(class = "sb-scroll", uiOutput("scoreboard")))),

      nav_panel(title = tagList(bs_icon("info-circle"), " About"), value = "about", uiOutput("aboutPanel"))
    )),
  div(class = "ddl-footer",
    div(tags$a(class = "custom-cta", href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Driver%20Cascade",
      span(class = "hand", "\U0001F44B"), "Want a custom data app like this for your project?")),
    p(style = "margin-top:12px", HTML("Built by <strong>Desert Data Labs</strong> · Tucson, AZ · "),
      tags$a(href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Driver%20Cascade", "desertdatalabs@gmail.com")),
    p(style = "font-size:12px;opacity:.85", "Synthesis of NEON DP1.10072.001 (small mammals), DP1.10003.001 (birds), DP1.10058.001 (plants), DP1.10098.001 (veg structure), DP1.10055.001 (phenology), and NEON/Daymet climate. Not affiliated with NEON, Battelle, or the NSF. An educational data-exploration tool."))
)
